version: '3.3'

services:
  plantuml-markdown:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MARKDOWN_VER=${MARKDOWN_VER:-3.4.1}
        - PYTHON_VER=${PYTHON_VER:-3.10}
    container_name: plantuml-markdown
    working_dir: /plantuml-markdown
    command: ['/bin/sh', '-c','nose2 --verbose -F']
    volumes:
      - .:/plantuml_markdown
      - ./plantuml_markdown.py:/usr/local/lib/python3.9/site-packages/plantuml_markdown.py
      - ./test:/plantuml-markdown/test
    stdin_open: true
    tty: true
    privileged: true

