version: '3.3'

services:
  plantuml-markdown:
    build:
      context: .
      args:
        - MARKDOWN_VER=${MARKDOWN_VER:-3.4.1}
        - PYTHON_VER=${PYTHON_VER:-3.10}
    command: ['/bin/sh', '-c', 'nose2 --verbose -F']
    volumes:
      - .:/plantuml_markdown
      - ./plantuml_markdown.py:/usr/local/lib/python${PYTHON_VER:-3.10}/site-packages/plantuml_markdown.py
      - ./test:/plantuml-markdown/test
