version: '3.3'

services:
  plantuml-markdown:
    build:
      context: .
      args:
        - MARKDOWN_VER=${MARKDOWN_VER:-3.4.1}
        - PYTHON_VER=${PYTHON_VER:-3.10}
    command: ['/bin/sh', '-c', 'pip3 install --force-reinstall /plantuml_markdown && /nose2 --verbose -F']
    volumes:
      - .:/plantuml_markdown
      - ./test:/plantuml-markdown/test
